<?php
/**
 * Добавление js и css файлов для модального окна.
 *
 */
 //drupal_add_js(drupal_get_path('module', 'example') . '/js/close-modal-click.js');

function _example_include_modal() {

  static $added = FALSE;
  if (!$added) {

    // Не добавлять библиотеки снова.
    $added = TRUE;

    // Подключаем Ctools библиотеки, которые нужны нам для задачи.
    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();
    //ctools_add_js('modal', 'example');

    // Создаем массив с настройками для модального окна.
    $example_style = array(
      'example-style' => array(
        'modalSize' => array(
          'type' => 'fixed',
          'width' => 650,
          'height' => 'auto',
          //'addWidth' => 70,
		  //'addHeight' => 700,
          'contentRight' => 30,
          'contentBottom' => 0,
        ),
        'modalOptions' => array(
          'opacity' => (float) 0.8,
          'background-color' => '#000000',
        ),
        'closeText' => '',
        'closeImage' => theme('image', array('path' => ctools_image_path('closeButton.png', 'example'))), // Картинка должна лежать в папке images нашего модуля.
        'animation' => 'fadeIn',
        'animationSpeed' => 'slow',
        'modalTheme' => 'my_custom_theme',
      ),
    );
    drupal_add_js($example_style, 'setting');
     //ctools_add_js('close_modal_click', 'example');
     ctools_add_js('my_custom_theme', 'example'); // Adding the theme (the first parameter is the theme file name, the second is the name of the module where this file is)
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function example_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state) {
  // Добавляем css класс для кнопки, чтобы сработали наши настройки для модального окна.
  $form['submit']['#attributes']['class'][] = 'ctools-modal-example-style';

  // Добавляем свой AJAX обработчик.
  $form['submit']['#ajax'] = array('callback' => 'example_add_to_cart_ajax_callback');

  // Добавляем свой обработчик после отправки формы.
  $form['#submit'][] = 'example_add_to_cart_form_submit';
}

/**
 * AJAX обработчик добавления товаров в корзину.
 */
function example_add_to_cart_ajax_callback($form, &$form_state) {
  // Подключаем библиотеки, необходимые для работы модального окна.
  _example_include_modal();

  // Убираем из вывода все друпалоские сообщения.
  drupal_get_messages();

  // Получаем обновленное содержимое корзины.
  $cart_block = module_invoke('commerce_cart', 'block_view', 'cart');

  // Формируем ссылки для закрытия модального окна и продолжения покупок,
  // а так же кнопку для перехода в корзину. На самом деле эти кнопки можно и во вьюз всунуть.
  $links = array();
  $links[] = '<span class="cart-link-center"><span class="cart-link-left">' . l('Продолжить покупки', '', array('attributes' => array('class' => array('button', 'ctools-close-modal', 'cart-link-right')))) . '</span></span>';
  $links[] = '<span class="cart-link-center"><span class="cart-link-left">' . l('Оформить заказ', 'cart', array('attributes' => array('class' => array('button', 'success', 'cart-link-right')))) . '</span></span>';

  // Создаем рендерный массив, который потом отдадим в модальное окно.
  $modal = array();

  // Загружаем ранее созданный вьюз, первый параметр машинное имя вьюза, второй машинное имя дисплея,
  // третий параметр это id добавляемого товара, который принимает вьюз в виде аргумента.
  $modal['product']['#markup'] = commerce_embed_view('product_added_to_cart', 'master', array($form_state['values']['product_id']));

  // Добавляем в рендерный массив ссылки, которые создали ранее.
  $modal['actions'] = array(
    '#theme' => 'item_list',
    '#items' => $links,
    '#attributes' => array(
      'class' => array('inline-list'),
    ),
  );

  // Формируем команды для AJAX.
  $commands = array();

  // Обновляем содержимое корзины.
  $commands[] = ajax_command_html('#block-commerce-cart-cart div.content', render($cart_block['content']));

  // Выводим модальное окно. Первый параметр, заголовок модального окна, второй - его содержимое.
  $commands[] = ctools_modal_command_display('Ваши покупки', render($modal));

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Обработчик отправки формы после добавления товаров в корзину.
 */
function example_add_to_cart_form_submit($form, &$form_state){
  $form_state['rebuild'] = TRUE;
}

/**
 * Closes modal windows.
 */
function exanple_dismiss($js = NULL) {
  if (!$js) {
    // we should never be here out of ajax context
    return MENU_NOT_FOUND;
  }

  ctools_include('modal');
  ctools_include('ajax');

  $output = array(ctools_modal_command_dismiss());

  print ajax_render($output);
}
